// actionTypes.js
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SAVE_PRAYER_RECORD = 'SAVE_PRAYER_RECORD';
export const LOAD_PRAYER_RECORDS = 'LOAD_PRAYER_RECORDS';
export const SET_STREAK_COUNT = 'SET_STREAK_COUNT';
export const RESET_STREAK_COUNT = 'RESET_STREAK_COUNT';
